### ISSUE TITLE
V 11 Compability 

### ISSUE THREAD

**Issue by MiguelWanderer** [flippelt/WnG-Apocrypha-FoundryVTT#8]
It is possible to have a version for V11

**Comment by SalithTaydan** [comment]
Would also like to see this updated. Currently have to set up an instance with v10 and then copy the compendiums so that when brought up to v11, they copies remain... and it's not an elegant solution.
Thank you.

**Comment by MeatMarionnette** [comment]
Same here please update :)

**Comment by SalithTaydan** [comment]
> Same here please update :)

Apparently you need to delete the module(s) and then reinstall them to Foundry and they work. (From the guy via Discord), an dit worked for me.

**Comment by flippelt** [comment]
Hello everyone, sorry I didn't answer before, this project was on hold since I was dealing with some mental health issues. With the release of the V9 of the apocrypha the module was updated to V11 and is being remade.
